---
- name: Managing Splunk docker
  hosts: docker_lxc

  tasks:
    - name: Managing folders
      ansible.builtin.file:
        mode: '0755'
        path: "{{ item }}"
        state: directory
      loop:
        - /splunk
        - /splunk/var
        - /splunk/etc
        - /splunk/etc/apps
        - /splunk/etc/apps/HASS_HEC
        - /splunk/tgz
        - /splunk/etc/apps/Valkyr_Presentation_MLTK

    - name: Copying the Splunk AIO docker-compose.yaml
      ansible.builtin.copy:
        src: "d_01_docker-compose.yaml"
        dest: "/splunk/docker-compose.yaml"
        mode: '0644'
      notify:
        - Stop_docker
        - Rebuild_docker
        - Restart_docker

    - name: Copying the compose secrets
      ansible.builtin.copy:
        src: "secrets.yml"
        dest: "/splunk/secrets.yml"
        mode: '0644'
      notify:
        - Stop_docker
        - Rebuild_docker
        - Restart_docker

    - name: Copying the Splunk HEC app
      ansible.builtin.copy:
        src: "apps/HASS_HEC"
        dest: "/splunk/etc/apps/"
        mode: '0644'
        owner: 41812
        group: 41812
      notify:
        - Stop_docker
        - Restart_docker

    - name: Copying the Splunk_SA_Scientific_Python_linux_x86_64
      ansible.builtin.copy:
        src: "tars/python-for-scientific-computing-for-linux-64-bit_422.tgz"
        dest: "/splunk/tgz/python.tgz"
      notify:
        - Extract_Splunk_SA_Scientific_Python_linux_x86_64
        - Stop_docker
        - Restart_docker

    - name: Copying the Splunk_ML_Toolkit app
      ansible.builtin.copy:
        src: "tars/splunk-machine-learning-toolkit_550.tgz"
        dest: "/splunk/tgz/mltk.tgz"
      notify:
        - Extract_Splunk_ML_Toolkit
        - Stop_docker
        - Restart_docker

    - name: Copying the Lookupeditor app
      ansible.builtin.copy:
        src: "tars/splunk-app-for-lookup-file-editing_405.tgz"
        dest: "/splunk/tgz/lookup_editor.tgz"
      notify:
        - Extract_lookup_editor
        - Stop_docker
        - Restart_docker

    - name: Copying the Presentation app
      ansible.builtin.copy:
        src: "apps/Valkyr_Presentation_MLTK"
        dest: "/splunk/etc/apps/"
        mode: '0644'
        owner: 41812
        group: 41812
      notify:
        - Stop_docker
        - Restart_docker

  handlers:
    - name: Extract_Splunk_SA_Scientific_Python_linux_x86_64
      ansible.builtin.unarchive:
        src: "/splunk/tgz/python.tgz"
        dest: "/splunk/etc/apps/"
        remote_src: yes
        mode: '0755'
        owner: 41812
        group: 41812

    - name: Extract_lookup_editor
      ansible.builtin.unarchive:
        src: "/splunk/tgz/lookup_editor.tgz"
        dest: "/splunk/etc/apps/"
        remote_src: yes
        mode: '0755'
        owner: 41812
        group: 41812

    - name: Extract_Splunk_ML_Toolkit
      ansible.builtin.unarchive:
        src: "/splunk/tgz/mltk.tgz"
        dest: "/splunk/etc/apps/"
        remote_src: yes
        mode: '0755'
        owner: 41812
        group: 41812

    - name: Stop_docker
      ansible.builtin.command:
        cmd: docker compose -f /splunk/docker-compose.yaml down
        chdir: /splunk
      # register: stop_splunk
      # changed_when: stop_splunk.stdout != ""
      # failed_when: stop_splunk.rc != 0

    - name: Rebuild_docker
      ansible.builtin.command:
        cmd: docker compose -f /splunk/docker-compose.yaml build
        chdir: /splunk
      # register: rebuild_splunk
      # changed_when: rebuild_splunk.stdout != ""
      # failed_when: rebuild_splunk.rc != 0
      # when: (stop_code.changed | default(false)) or code_service_status.changed

    - name: Restart_docker
      ansible.builtin.command:
        cmd: docker compose -f /splunk/docker-compose.yaml up -d
        chdir: /splunk
      # register: restart_code
      # when: (stop_code.changed | default(false)) or code_service_status.changed
      # changed_when: restart_code.stdout != ""
      # failed_when: restart_code.rc != 0
