services:
  so1:
    image: ${SPLUNK_IMAGE:-splunk/splunk:9.3.4}
    container_name: so1
    environment:
      - SPLUNK_START_ARGS=--accept-license
    env_file:
      - ./secrets.yml
    ports:
      - 8000:8000
      - 8088:8088
      - 8089:8089
    networks:
      - splunk_network
      - default
    volumes:
      - /splunk/var/:/opt/splunk/var
      - /splunk/etc/apps/HASS_HEC/:/opt/splunk/etc/apps/HASS_HEC/

networks:
  splunk_network:
    internal: true